---
kind: pipeline
type: docker
name: deploy

steps:
  - name: publish
    image: plugins/ecr
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      repo: streetrunner_bot
      registry: 166683195216.dkr.ecr.us-east-1.amazonaws.com