name: Deploy to EBS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
      - uses: schdck/create-env-json@v2
        with:
          file-name: 'env.json'
          VERSION: ${{ github.sha }}
      - run: zip -9 -r deploy.zip . -x '*.git*'
      - uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: streetrunner-bot
          environment_name: streetrunner-bot-env
          version_label: ${{ github.sha }}
          region: ap-southeast-1
          deployment_package: deploy.zip
