name: Test

on: [push, pull_request]

env:
  PYTHONPATH: ${{ github.workspace }}
  BASIC_USER: ''
  BASIC_PASS: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Test Bot
        run: python bot/main.py test